# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.srcs/sources_1/ip/ram_4096_27/ram_4096_27.xci
# IP: The module: 'ram_4096_27' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.gen/sources_1/ip/ram_4096_27/ram_4096_27_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_4096_27'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.srcs/sources_1/ip/ram_4096_27/ram_4096_27.xci
# IP: The module: 'ram_4096_27' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.gen/sources_1/ip/ram_4096_27/ram_4096_27_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_4096_27'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
