# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.srcs/sources_1/ip/fifo_128_50/fifo_128_50.xci
# IP: The module: 'fifo_128_50' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.gen/sources_1/ip/fifo_128_50/fifo_128_50.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128_50'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.gen/sources_1/ip/fifo_128_50/fifo_128_50_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.srcs/sources_1/ip/fifo_128_50/fifo_128_50.xci
# IP: The module: 'fifo_128_50' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.gen/sources_1/ip/fifo_128_50/fifo_128_50.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/SourceCode/Xilinx/ErrorFunnel/ErrorFunnel.gen/sources_1/ip/fifo_128_50/fifo_128_50_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128_50'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
